resources:
- name: github-cr-golang-build-container
  type: git
  source:
    uri: https://github.com/Bit-Clouded/CitrusRind.git
    branch: ci/concourse
    paths: ['build-images/golang/*']
- name: github-cr-alb-rule-assigner
  type: git
  source:
    uri: https://github.com/Bit-Clouded/CitrusRind.git
    branch: ci/concourse
    paths: ['alb-rule-assigner/*', 'alb-rule-assigner/**/*']

- name: golang-build-container
  type: docker-image
  source:
    repository: 458712717391.dkr.ecr.us-west-2.amazonaws.com/test

jobs:
  - name: build-container
    public: true
    plan:
      - get: github-cr-golang-build-container
        trigger: false
      - put: golang-build-container
        params:
          build: github-cr-golang-build-container/build-images/golang
  - name: build-lambda
    public: true
    plan:
      - get: golang-build-container
        trigger: true
      - get: github-cr-alb-rule-assigner
        trigger: true
      - task: build
        image: golang-build-container
        config:
          platform: linux
          inputs:
            - name: github-cr-alb-rule-assigner
              path: /
          run:
            path: /bin/sh
            dir: alb-rule-assigner
            args:
              - -c
              - |
                go get -d ./...
                go build -v -ldflags '-d -s -w' -a -tags netgo -installsuffix netgo -o main .
                zip ../lambda-zip/main.zip main
          outputs:
            - name: lambda-zip
      - task: ls
        image: golang-build-container
        config:
          platform: linux
          inputs:
            - name: lambda-zip
          run:
            path: /bin/sh
            args:
              - -c
              - |
                ls
